name: Checkout
description: "This is a wrapper to actions/checkout that fallbacks to the default branch if the ref does not exist."

inputs:
  fetch-depth:
    default: "1"
    required: false
    description: "fetch-depth"
  path:
    default: ''
    required: false
    description: "path"
  repository:
    default: ${{ github.repository }}
    required: false
    description: "repository"
  ref:
    default: ''
    required: false
    description: "ref"
  token:
    default: ${{ github.token }}
    required: false
    description: "token"

runs:
  using: composite

  steps:
    - id: repo
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        if [[ -z "${{ inputs.ref }}" ]]
        then
          if [[ "${{ inputs.repository }}" != "${{ github.repository }}" ]]
          then
            USING="default branch"
          else
            GITHUB_SHA_TO_USE="${{ github.sha }}"
            if [[ "${{ github.event_name }}" == "pull_request" ]]
            then
              GITHUB_SHA_TO_USE="${{ github.event.pull_request.head.sha }}"
            fi
            USING="$(gh api /repos/${{ inputs.repository }}/commits/${GITHUB_SHA_TO_USE}/branches-where-head --jq '.[0].name')"
          fi
          echo "::notice::Checkout: ${{ inputs.repository }} using ${USING}"
          echo "ref-exists=true" >> $GITHUB_OUTPUT
        
        else
          if git ls-remote --heads --quiet --exit-code https://${{ inputs.token }}@github.com/${{ inputs.repository }}.git ${{ inputs.ref }}
          then
            echo "::notice::Checkout: ${{ inputs.repository }} using ${{ inputs.ref }}"
            echo "ref-exists=true" >> $GITHUB_OUTPUT
          else
            USING="$(gh api /repos/${{ inputs.repository }} --jq '.default_branch')"
            echo "::notice::Checkout: ${{ inputs.repository }} does not have ref ${{ inputs.ref }} (fallback to ${USING})"
            echo "ref-exists=false" >> $GITHUB_OUTPUT
            echo "default-branch=${USING}" >> $GITHUB_OUTPUT
          fi
        fi

    - if: steps.repo.outputs.ref-exists == 'true'
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        path: ${{ inputs.path }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}

    - if: steps.repo.outputs.ref-exists == 'false'
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        path: ${{ inputs.path }}
        repository: ${{ inputs.repository }}
        ref: ${{ steps.repo.outputs.default-branch }}
        token: ${{ inputs.token }}
